### PR TITLE
Typescript Fixes

### PR DESCRIPTION
**Pull request by uxder**
This fixes several issues:
- the JS is not loading (/dist/js/ is not static route)
- Add footprint to JS
- Add `declaration: false` to prevent .d.ts file generation in builds.

### CODE REVIEW

**Comment by uxder** [comment]
@jeremydw FYI.

**Comment by jeremydw** [comment]
LGTM thank you. I added an Issue on Amagaki to add a `fingerprint` property to static files so we don't need to do the `?cb=` thing anymore: 

https://github.com/blinkkcode/amagaki/issues/52

**Comment by uxder** [comment]
Ah okay, I'll make a push to revert the cb.

**Comment by jeremydw** [comment]
Ah no, we don't have the feature yet so it's OK to leave in. :)

**Pull request merged**
